name: Build mcollection (Surge & Loon)

on:
  push:
    paths:
      - 'surge/*.sgmodule'
      - 'loon/*.plugin'
      - 'scripts/**'
      - '.github/workflows/build-mcollection.yml'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build Surge mcollection
        run: node scripts/build-collection-surge.js

      - name: Build Loon mcollection
        run: node scripts/build-collection-loon.js

      - name: Commit & Push if changed
        run: |
          set -e
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add surge/mcollection.sgmodule || true
            git add loon/mcollection.plugin    || true
            git commit -m "chore: auto-build mcollection ($(date +'%Y-%m-%d %H:%M:%S'))"
            git push
          else
            echo "No changes to commit."
          fi
