name: Cron Dispatch (hourly at :18)

on:
  schedule:
    - cron: '18 * * * *'   # 每小时第 18 分钟（UTC/SGT）
  workflow_dispatch:       # 手动兜底

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Emit repository_dispatch: kick_mcollection
        uses: actions/github-script@v7
        with:
          script: |
            await github.request('POST /repos/{owner}/{repo}/dispatches', {
              owner: context.repo.owner,
              repo: context.repo.repo,
              event_type: 'kick_mcollection',
              client_payload: { source: 'cron-18' }
            })
