name: Build M3U (valid-only with icons)

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build M3U (valid-only with icons)
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Settings → Secrets → Actions 里配好
          3U_FILTER: strict        # strict / loose / off
          EST_TOTAL_LIMIT: "50"    # 0 = 全量
        run: node m3u.js
