name: Update Scripts List

on:
  push:
    branches: [main]
    paths:
      - 'input/**'
      - 'loon/**'
      - 'quantumultx/**'
      - 'surge/**'
  workflow_dispatch:

jobs:
  update-scripts:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Generate scripts list
        run: |
          mkdir -p input quantumultx loon surge
          # 确保在仓库根目录运行
          cd ${{ github.workspace }}
          node scripts/generate-script-list.js
          echo "=== 检查生成的文件 ==="
          ls -la *.json || echo "根目录没有 JSON 文件"
          echo "=== 显示文件内容 ==="
          if [ -f "scripts.json" ]; then
            echo "找到 scripts.json，内容："
            cat scripts.json
          else
            echo "未找到 scripts.json 文件"
          fi
          
      - name: Deploy to GitHub Pages
        run: |
          echo "=== 准备部署文件 ==="
          ls -la scripts.json
          
          # 设置 git 配置
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # 将文件添加到 git
          git add scripts.json
          
          # 检查是否有变更
          if git diff --staged --quiet; then
            echo "没有变更需要提交"
          else
            echo "提交变更到 main 分支"
            git commit -m "Update scripts.json - $(date '+%Y-%m-%d %H:%M:%S')"
            git push origin main
          fi
