name: Update Scripts List

on:
  push:
    branches: [main]
    paths:
      - 'input/**'
      - 'loon/**'
      - 'quantumultx/**'
      - 'surge/**'
  workflow_dispatch:

jobs:
  update-scripts:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Generate scripts list
        run: |
          mkdir -p input quantumultx loon surge
          node scripts/generate-script-list.js
          echo "=== 检查生成的文件 ==="
          ls -la *.json || echo "根目录没有 JSON 文件"
          find . -name "scripts.json" -type f
          echo "=== 显示文件内容 ==="
          if [ -f "scripts.json" ]; then
            cat scripts.json
          else
            echo "未找到 scripts.json 文件"
          fi
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          keep_files: true
          include_only: |
            scripts.json
            input/
            quantumultx/
            loon/
            surge/
