name: Update Scripts List

on:
  push:
    branches: [main]
    paths:
      - 'input/**'
      - 'loon/**'
      - 'quantumultx/**'
      - 'surge/**'
  workflow_dispatch:

jobs:
  update-scripts:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Generate scripts list
        run: |
          mkdir -p input quantumultx loon surge
          node scripts/generate-script-list.js
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          keep_files: true
          include_only: |
            scripts.json
            input/
            quantumultx/
            loon/
            surge/
